server:
  port: 4000

spring:
  application:
    name: Backend Assignment

firebase:
  web-key: ${FIREBASE_WEB_KEY}
  private-key-src: ${FIREBASE_PRIVATE_KEY}
  web-url: https://identitytoolkit.googleapis.com/v1/accounts:signInWithPassword